import Head from "next/head";
import Link from "next/link";
import IntroMessage from "../components/IntroMessage";
import SignIn from "../components/SignIn";
import InputFlex from "../components/InputFlex";
import PrimaryButton from "../components/PrimaryButton";
import { UserIcon } from "../components/Icons/UserIcon";
import { LockIcon } from "../components/Icons/LockIcon";

export default function Home() {
  return (
    <>
      <Head>
        <title>Deallus App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <div className="max-w-[826px] mx-auto">
          <div className="max-w-[826px] mx-auto bg-white rounded-md border border-offWhite">
            <SignIn signInText="SIGN IN" />
            <div className="lg:ml-20 ml-4 lg:mr-20 mr-4">
              <IntroMessage
                welcome="Welcome back!"
                provideInfo="Please provide valid information to login to your account"
              />
              <InputFlex
                placeholder="Enter username"
                type="text"
                closeIcon="closeIcon"
                icon={<UserIcon className="stroke-current " />}
              />

              <InputFlex
                icon={<LockIcon className="stroke-current " />}
                placeholder="Enter password"
                type="password"
                
              />

              <PrimaryButton btnText="SIGN IN" />

              <div className="my-10 mb-10 mt-10  lg:flex-row flex flex-col justify-between items-center ">
                <p className="text-xl text-blueText mb-10">
                  <Link href="/sign-up-forgot">I can’t login, help me</Link>
                </p>
                <p className="text-xl text-lightBlue mb-10">
                  <Link href="/sign-up"> Don’t have an account?</Link>{" "}
                  <br className="lg:hidden" />{" "}
                  <Link href="/sign-up">Sign up here</Link>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
